"""add_user_fields

Revision ID: 61ae62d1d268
Revises: 001_initial
Create Date: 2026-01-05 09:07:15.734249+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61ae62d1d268'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('admin_users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('admin_users', sa.Column('last_login_ip', sa.String(length=50), nullable=True))
    op.add_column('admin_users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('admin_users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('admin_users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    
    # Explicitly create the enum type first
    admin_role = sa.Enum('OWNER', 'ADMIN', 'SUPPORT', name='admin_role')
    admin_role.create(op.get_bind(), checkfirst=True)

    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=admin_role,
               existing_nullable=False,
               postgresql_using='role::admin_role')
               
    op.alter_column('admin_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('admin_users_email_key', 'admin_users', type_='unique')
    op.drop_constraint('admin_users_username_key', 'admin_users', type_='unique')
    op.drop_index('ix_admin_users_email', table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.drop_index('ix_admin_users_username', table_name='admin_users')
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_index(op.f('ix_admin_users_role'), 'admin_users', ['role'], unique=False)
    op.drop_column('admin_users', 'last_login')
    op.drop_column('admin_users', 'full_name')
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='resource_id::uuid')
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.add_column('device_sessions', sa.Column('vpn_account_id', sa.UUID(), nullable=False))
    op.add_column('device_sessions', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('device_sessions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('device_sessions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('device_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('device_sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=postgresql.INET(),
               existing_nullable=True,
               postgresql_using='ip_address::inet')
    op.create_index(op.f('ix_device_sessions_ended_at'), 'device_sessions', ['ended_at'], unique=False)
    op.create_index(op.f('ix_device_sessions_started_at'), 'device_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_device_sessions_vpn_account_id'), 'device_sessions', ['vpn_account_id'], unique=False)
    op.create_foreign_key(None, 'device_sessions', 'vpn_accounts', ['vpn_account_id'], ['id'])
    op.add_column('devices', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('devices', sa.Column('vpn_account_id', sa.UUID(), nullable=True))
    op.add_column('devices', sa.Column('device_token', sa.String(length=100), nullable=False))
    op.add_column('devices', sa.Column('device_fingerprint', sa.String(length=500), nullable=True))
    op.add_column('devices', sa.Column('device_name', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('device_model', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('os_version', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('is_token_used', sa.Boolean(), nullable=False))
    op.add_column('devices', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('last_ip', postgresql.INET(), nullable=True))
    op.add_column('devices', sa.Column('connection_count', sa.Integer(), nullable=False))
    op.add_column('devices', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('devices', 'device_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_devices_binding_token', table_name='devices')
    op.create_index(op.f('ix_devices_device_token'), 'devices', ['device_token'], unique=True)
    op.create_index(op.f('ix_devices_is_active'), 'devices', ['is_active'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_index(op.f('ix_devices_vpn_account_id'), 'devices', ['vpn_account_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'vpn_accounts', ['vpn_account_id'], ['id'])
    op.create_foreign_key(None, 'devices', 'users', ['user_id'], ['id'])
    op.drop_column('devices', 'fingerprint')
    op.drop_column('devices', 'binding_token_expires_at')
    op.drop_column('devices', 'protocol')
    op.drop_column('devices', 'last_seen_at')
    op.drop_column('devices', 'name')
    op.drop_column('devices', 'device_id')
    op.drop_column('devices', 'binding_token')
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=False))
    
    notification_type = sa.Enum('PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'SUBSCRIPTION_EXPIRING', 'SUBSCRIPTION_EXPIRED', 'SUBSCRIPTION_RENEWED', 'DEVICE_LIMIT_REACHED', 'SERVER_MAINTENANCE', 'REFERRAL_REWARD', 'PROMO_CODE', 'GENERAL', name='notification_type')
    notification_type.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=notification_type,
               existing_nullable=False,
               postgresql_using='type::notification_type')
               
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.add_column('payments', sa.Column('plan_id', sa.UUID(), nullable=False))
    op.add_column('payments', sa.Column('promo_code_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payments', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payments', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('payment_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('payments', sa.Column('refunded_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    
    payment_status = sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CHARGEBACK', 'CANCELLED', name='payment_status')
    payment_status.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=payment_status,
               existing_nullable=False,
               postgresql_using='status::payment_status')
               
    op.alter_column('payments', 'payment_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_payments_plan_id'), 'payments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'promo_codes', ['promo_code_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'plans', ['plan_id'], ['id'])
    op.drop_column('payments', 'provider')
    op.add_column('plans', sa.Column('bandwidth_limit', sa.BigInteger(), nullable=True))
    op.add_column('plans', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('plans', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_plans_sort_order'), 'plans', ['sort_order'], unique=False)
    op.drop_column('plans', 'traffic_limit_gb')
    op.drop_column('plans', 'speed_limit_mbps')
    op.add_column('promo_codes', sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discount_type'), nullable=False))
    op.add_column('promo_codes', sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('promo_codes', sa.Column('plan_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.add_column('promo_codes', sa.Column('min_purchase_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('promo_codes', sa.Column('max_uses_per_user', sa.Integer(), nullable=False))
    op.add_column('promo_codes', sa.Column('starts_at', sa.DateTime(), nullable=True))
    op.add_column('promo_codes', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('promo_codes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('promo_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('promo_codes_code_key', 'promo_codes', type_='unique')
    op.drop_index('ix_promo_codes_code', table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_index(op.f('ix_promo_codes_expires_at'), 'promo_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_promo_codes_is_active'), 'promo_codes', ['is_active'], unique=False)
    op.drop_column('promo_codes', 'discount_percent')
    op.drop_column('promo_codes', 'valid_until')
    op.drop_column('promo_codes', 'discount_amount')
    op.drop_column('promo_codes', 'valid_from')
    op.add_column('referrals', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REWARDED', name='referral_status'), nullable=False))
    op.add_column('referrals', sa.Column('reward_currency', sa.String(length=3), nullable=True))
    op.add_column('referrals', sa.Column('rewarded_at', sa.DateTime(), nullable=True))
    op.add_column('referrals', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('referrals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_referrals_referred_id', table_name='referrals')
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=True)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.drop_column('referrals', 'reward_paid')
    op.add_column('server_groups', sa.Column('regions', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('server_groups', sa.Column('load_balancing_strategy', sa.Enum('LEAST_LOADED', 'ROUND_ROBIN', 'GEO_CLOSEST', name='load_balancing_strategy'), nullable=False))
    op.add_column('server_groups', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('server_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('server_groups', 'is_active')
    op.drop_column('server_groups', 'country_code')
    op.add_column('servers', sa.Column('region', sa.String(length=100), nullable=False))
    op.add_column('servers', sa.Column('hostname', sa.String(length=255), nullable=True))
    op.add_column('servers', sa.Column('ip_address', postgresql.INET(), nullable=False))
    op.add_column('servers', sa.Column('ipv6_address', postgresql.INET(), nullable=True))
    op.add_column('servers', sa.Column('management_type', sa.Enum('AGENT', 'SSH', name='management_type'), nullable=False))
    op.add_column('servers', sa.Column('agent_url', sa.String(length=500), nullable=True))
    op.add_column('servers', sa.Column('agent_token', sa.Text(), nullable=True))
    op.add_column('servers', sa.Column('ssh_host', sa.String(length=255), nullable=True))
    op.add_column('servers', sa.Column('ssh_port', sa.Integer(), nullable=True))
    op.add_column('servers', sa.Column('ssh_user', sa.String(length=100), nullable=True))
    op.add_column('servers', sa.Column('ssh_key', sa.Text(), nullable=True))
    op.add_column('servers', sa.Column('max_bandwidth', sa.BigInteger(), nullable=True))
    op.add_column('servers', sa.Column('current_bandwidth', sa.BigInteger(), nullable=False))
    op.add_column('servers', sa.Column('health_check_url', sa.String(length=500), nullable=True))
    op.add_column('servers', sa.Column('health_check_failures', sa.Integer(), nullable=False))
    op.add_column('servers', sa.Column('drain_mode', sa.Boolean(), nullable=False))
    op.add_column('servers', sa.Column('server_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('servers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    
    server_status = sa.Enum('HEALTHY', 'DEGRADED', 'OFFLINE', 'MAINTENANCE', name='server_status')
    server_status.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('servers', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=server_status,
               existing_nullable=False,
               postgresql_using='status::server_status')
               
    op.alter_column('servers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_servers_host', table_name='servers')
    op.create_index(op.f('ix_servers_current_users'), 'servers', ['current_users'], unique=False)
    op.create_index(op.f('ix_servers_is_active'), 'servers', ['is_active'], unique=False)
    op.create_index(op.f('ix_servers_region'), 'servers', ['region'], unique=False)
    op.drop_constraint('servers_group_id_fkey', 'servers', type_='foreignkey')
    op.drop_column('servers', 'host')
    op.drop_column('servers', 'network_download')
    op.drop_column('servers', 'memory_usage')
    op.drop_column('servers', 'cpu_usage')
    op.drop_column('servers', 'disk_usage')
    op.drop_column('servers', 'agent_port')
    op.drop_column('servers', 'group_id')
    op.drop_column('servers', 'network_upload')
    op.drop_column('servers', 'agent_secret_key')
    op.add_column('subscriptions', sa.Column('server_id', sa.UUID(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    
    subscription_status = sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED', name='subscription_status')
    subscription_status.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=subscription_status,
               existing_nullable=False,
               postgresql_using='status::subscription_status')
               
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_server_id'), 'subscriptions', ['server_id'], unique=False)
    op.drop_constraint('subscriptions_vpn_account_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'servers', ['server_id'], ['id'])
    op.drop_column('subscriptions', 'vpn_account_id')
    op.drop_column('subscriptions', 'cancelled_at')
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('ban_reason', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(length=50), nullable=True))
    op.alter_column('users', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_referrer_id'), 'users', ['referrer_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['referral_code'])
    op.drop_column('users', 'is_active')
    op.add_column('vpn_accounts', sa.Column('subscription_id', sa.UUID(), nullable=False))
    op.add_column('vpn_accounts', sa.Column('config', sa.Text(), nullable=False))
    op.add_column('vpn_accounts', sa.Column('private_key', sa.Text(), nullable=True))
    op.add_column('vpn_accounts', sa.Column('ip_address', postgresql.INET(), nullable=True))
    op.add_column('vpn_accounts', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', name='vpn_account_status'), nullable=False))
    op.add_column('vpn_accounts', sa.Column('bandwidth_used', sa.BigInteger(), nullable=False))
    op.add_column('vpn_accounts', sa.Column('last_connected_at', sa.DateTime(), nullable=True))
    op.add_column('vpn_accounts', sa.Column('connection_count', sa.Integer(), nullable=False))
    op.add_column('vpn_accounts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    
    vpn_protocol = sa.Enum('WIREGUARD', 'OPENVPN', 'AMNEZIA', name='vpn_protocol')
    vpn_protocol.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('vpn_accounts', 'protocol',
               existing_type=sa.VARCHAR(length=50),
               type_=vpn_protocol,
               existing_nullable=False,
               postgresql_using='protocol::vpn_protocol')
               
    op.alter_column('vpn_accounts', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vpn_accounts', 'public_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('vpn_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_vpn_accounts_user_id', table_name='vpn_accounts')
    op.drop_index('ix_vpn_accounts_username', table_name='vpn_accounts')
    op.create_index(op.f('ix_vpn_accounts_protocol'), 'vpn_accounts', ['protocol'], unique=False)
    op.create_index(op.f('ix_vpn_accounts_server_id'), 'vpn_accounts', ['server_id'], unique=False)
    op.create_index(op.f('ix_vpn_accounts_status'), 'vpn_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_vpn_accounts_subscription_id'), 'vpn_accounts', ['subscription_id'], unique=False)
    op.drop_constraint('vpn_accounts_user_id_fkey', 'vpn_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'vpn_accounts', 'subscriptions', ['subscription_id'], ['id'])
    op.drop_column('vpn_accounts', 'is_active')
    op.drop_column('vpn_accounts', 'user_id')
    op.drop_column('vpn_accounts', 'client_ip')
    op.drop_column('vpn_accounts', 'bytes_sent')
    op.drop_column('vpn_accounts', 'config_encrypted')
    op.drop_column('vpn_accounts', 'bytes_received')
    op.drop_column('vpn_accounts', 'last_handshake')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass  # Downgrade not implemented for this migration
